apiVersion: v1
kind: Service
metadata:
  name: {{ include "zipline.fullname" . }}
  labels:
    {{- include "zipline.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.coreConfig.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "zipline.selectorLabels" . | nindent 4 }}
