apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "v-rising.fullname" . }}
  labels:
    {{- include "v-rising.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "v-rising.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "v-rising.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "v-rising.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.image }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: gameport
              containerPort: {{ .Values.service.gamePort }}
              protocol: UDP
            - name: queryport
              containerPort: {{ .Values.service.queryPort }}
              protocol: UDP
          env:
            - name: TZ
              value: {{ .Values.vrising.timezone }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/mnt/vrising/persistentdata"
              name: {{ include "v-rising.fullname" . }}-world
            - mountPath: "/mnt/vrising/server"
              name: {{ include "v-rising.fullname" . }}-server-data
      volumes:
        - name: {{ include "v-rising.fullname" . }}-world
          {{- if .Values.persistence.config.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "v-rising.fullname" . }}-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: {{ include "v-rising.fullname" . }}-server-data
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
