{{- if .Values.persistence.config.enabled }}
{{- $fullName := include "v-rising.fullname" . -}}
{{- with .Values.persistence }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $fullName }}-pvc
  annotations:
      {{- if .config.retain }}
    "helm.sh/resource-policy": keep
      {{- end }}
spec:
  resources:
    requests:
      storage: {{ .config.size }}
  accessModes:
    - ReadWriteOnce
{{- end }}
{{- end }}
