apiVersion: v1
kind: Service
metadata:
  name: {{ include "v-rising.fullname" . }}
  labels:
    {{- include "v-rising.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.gamePort }}
      targetPort: 9876
      protocol: UDP
      name: 'game-port'
    - port: {{ .Values.service.queryPort }}
      targetPort: 9877
      protocol: UDP
      name: 'query-port'
  selector:
    {{- include "v-rising.selectorLabels" . | nindent 4 }}
